In [1]:
import pandas as pd
import plotly
import plotly.express as px

In [2]:
df = pd.read_excel("/mnt/data/Dexcom_Readings/DexcomG8Domino.xlsx")

In [4]:
display(df)

              Timestamp  Glucose Level (mg/dL)    Trend   Alert
0   2024-04-24 00:00:00                  126.5   Stable  Normal
1   2024-04-24 00:05:00                  106.0   Rising  Normal
2   2024-04-24 00:10:00                  114.7   Stable  Normal
3   2024-04-24 00:15:00                  133.6  Falling  Normal
4   2024-04-24 00:20:00                  128.0   Stable  Normal
..                  ...                    ...      ...     ...
283 2024-04-24 23:35:00                  123.0   Stable  Normal
284 2024-04-24 23:40:00                  104.3   Stable  Normal
285 2024-04-24 23:45:00                  109.1   Stable  Normal
286 2024-04-24 23:50:00                   84.3   Stable  Normal
287 2024-04-24 23:55:00                  118.2  Falling  Normal

[288 rows x 4 columns]